# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

icalendar:
  calendars:
    - entity_id: calendar.sms
      secret: test
      colour: black
  colours:
    - name: "Recycling"
      colour: green
    - name: "Food waste"
      colour: brown

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.icalendar: debug

debugpy:
  host: localhost # Optional
  port: 5678 # Optional
  start: true
  wait: true  # Force wait for remote debugging